name: Generate Keystore

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/generate-keystore.yml'


jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Keystore
        run: |
          keytool -genkey -v \
            -keystore almalibre-release.keystore \
            -alias almalibre \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass AlmaLibre2025 \
            -keypass AlmaLibre2025 \
            -dname "CN=Almalibre, OU=Development, O=Almalibre, L=Malaga, ST=Malaga, C=ES"

      - name: Upload Keystore
        uses: actions/upload-artifact@v4
        with:
          name: keystore
          path: almalibre-release.keystore
